// common
export const CHANGE_ENDPOINT_LOADING_STATE = 'CHANGE_ENDPOINT_LOADING_STATE';

// list
export const FILL_LIST = 'FILL_LIST';
export const FILL_LIST_EMPLOYEES = 'FILL_LIST_EMPLOYEES';
export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';
export const EDIT_LIST_ITEM = 'EDIT_LIST_ITEM';
export const CHANGE_LIST_ITEM_PROCESS_STATE = 'CHANGE_LIST_ITEM_PROCESS_STATE';
